---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: jsadmissions-default
rules:
  - apiGroups: [ "" ]
    resources: [ "pods" ]
    verbs: [ "get", "watch", "list" ]
  - apiGroups: [ "momiji.com" ]
    resources: [ "jsadmissions", "clusterjsadmissions" ]
    verbs: [ "get","watch","list" ]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: jsadmissions
  namespace: kube-jsadmissions
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: jsadmissions-default
subjects:
  - kind: ServiceAccount
    name: jsadmissions
    namespace: kube-jsadmissions
roleRef:
  kind: ClusterRole
  name: jsadmissions-default
  apiGroup: rbac.authorization.k8s.io
